# Generated by Django 5.0 on 2023-12-15 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('jpg', 'JPG'), ('jpeg', 'JPEG')], max_length=4)),
            ],
        ),
    ]
