# Generated by Django 5.0 on 2023-12-15 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('image', '0001_initial'),
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('set', 'Set'), ('approved', 'Approved'), ('delivered', 'Delivered')], max_length=16)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.image')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mark.mark')),
            ],
        ),
    ]
